version: '3'

services:
  docker-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  standard-api:
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

